app: dish-api
service: dish-api-service

provider:
  name: aws
  runtime: nodejs8.10

  region: us-east-1
  profile: personal

resources:
  # DynamoDB
  - ${file(resources/dynamo-db.yml)}

functions:
  ListDishes:
    handler: handler.listDishes
    events:
      - http:
          path: /list
          method: get
  AddDish:
    handler: handler.addUpdateDish
    events:
      - http:
          path: /new
          method: post
  UpdateDish:
    handler: handler.addUpdateDish
    events:
      - http:
          path: /update
          method: put
  DeleteDish:
    handler: handler.deleteDish
    events:
      - http:
          path: /remove
          method: delete
