app: webhooks
service: webhooks-app

provider:
  name: aws
  runtime: nodejs8.10

  region: us-east-1
  profile: personal

plugins:
  - serverless-offline

resources:
  # DynamoDB
  - ${file(resources/dynamo-db.yml)}

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem

functions:
  storeImages:
    handler: handler.storeImages
    events:
      - http:
          path: /
          method: post
          cors: true
