app: webhooks
service: webhooks-app

provider:
  name: aws
  runtime: nodejs8.10

  region: us-east-1
  profile: personal

plugins:
  - serverless-offline

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
    Resource: arn:aws:dynamodb:us-east-1:514260427086:table/images

functions:
  storeImages:
    handler: handler.storeImages
    events:
      - http:
          path: /
          method: post
          cors: true

resources:
  # DynamoDB
  - ${file(resources/dynamo-db.yml)}
