org: ajejoseph22
app: driedel
service: dreidel-app

provider:
  name: aws
  runtime: nodejs8.10

  region: us-east-1
  profile: personal

functions:
  Spinner: #Spinner function
    handler: handler.spin
    events:
      - http:
          path: /
          method: get
